import type { Report, RuleMeta } from "./types";

function authority(meta: RuleMeta): string {
  return meta.authority?.length ? ` (per ${meta.authority.map((a) => `${a.name}: ${a.url}`).join("; ")})` : "";
}

/** A complete, human-readable Markdown report covering every finding in every
 * tier — what you'd paste into an issue or hand to a reviewer. */
export function reportToMarkdown(r: Report): string {
  const c = r.counts;
  const out: string[] = [];
  out.push(`# blacklight audit — ${r.target}`, "");
  out.push(`${c.total} findings across ${r.scanned} files: ${c.security} security, ${c.correctness} correctness, ${c.bestPractice} best-practice.`);
  out.push(`Tiers: ${c.quickWin} quick wins, ${c.needsReview} needs review, ${c.reportOnly} report-only.`, "");

  if (r.quickWins.length) {
    out.push(`## Quick wins (${c.quickWin}) — ready to apply`, "");
    for (const f of r.quickWins) {
      out.push(`### \`${f.file}\``);
      for (const m of f.addressed) out.push(`- **${m.id}** ${m.title}${authority(m)}`);
      for (const n of f.needsInput) out.push(`- **${n.checkId}** (needs a value) — ${n.meta.remediation}`);
      if (f.diff) out.push("", "```diff", f.diff, "```");
      out.push("");
    }
  }

  if (r.needsReview.length) {
    out.push(`## Needs review (${c.needsReview}) — judgement / agent`, "");
    for (const cl of r.needsReview) {
      out.push(`### ${cl.name}`);
      for (const { meta, findings } of cl.rules) {
        out.push(`- **${meta.id}** — ${meta.title}. ${meta.remediation}${authority(meta)}`);
        for (const fi of findings) out.push(`  - \`${fi.file}\`${fi.entity ? ` (${fi.entity})` : ""} — ${fi.message}`);
      }
      out.push("");
    }
  }

  if (r.reportOnly.length) {
    out.push(`## Report-only (${c.reportOnly}) — hygiene`, "");
    out.push("| Rule | Title | File | Detail |", "| --- | --- | --- | --- |");
    for (const f of r.reportOnly) {
      out.push(`| ${f.checkId} | ${f.meta.title} | \`${f.file}\` | ${f.message.replace(/\|/g, "\\|")} |`);
    }
    out.push("");
  }

  out.push("---", `Generated by blacklight — https://blacklight.intentius.io`);
  return out.join("\n");
}

function slug(target: string): string {
  return target.replace(/^https?:\/\//, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "report";
}

function trigger(name: string, type: string, body: string): void {
  const url = URL.createObjectURL(new Blob([body], { type }));
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

export function downloadMarkdown(r: Report): void {
  trigger(`blacklight-${slug(r.target)}.md`, "text/markdown", reportToMarkdown(r));
}

export function downloadJson(r: Report): void {
  trigger(`blacklight-${slug(r.target)}.json`, "application/json", JSON.stringify(r, null, 2));
}
